# docker-compose.yml
version: '2'

services:
  web:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
     - 5000:5000
    depends_on:
      - db
  db:
    image: mysql:9.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data:

